services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: trihub
      POSTGRES_USER: trihub
      POSTGRES_PASSWORD: trihub
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trihub -d trihub"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    env_file: .env.dev
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:
