# Generated by Django 5.2.7 on 2025-10-24 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Adresse"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("none", "Aucune"),
                            ("weekly", "Hebdomadaire"),
                            ("same_type", "Semaines du même type que la première"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Date de fin (incluse), en heure locale Paris"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Récurrence",
                "verbose_name_plural": "Récurrences",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_head_coach",
                    models.BooleanField(default=False, verbose_name="Coach Principal"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qualifications",
                    models.ManyToManyField(
                        blank=True, to="core.category", verbose_name="Peut encadrer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Licencié",
                "verbose_name_plural": "Licenciés",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="CoachAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmé"),
                            ("withdrawn", "Désinscrit"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance×Coach",
                "verbose_name_plural": "Séance×Coach",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="Jour et Horaire")),
                (
                    "duration_min",
                    models.PositiveIntegerField(default=60, verbose_name="Durée"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "min_coaches",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Encadrants minimum"
                    ),
                ),
                (
                    "constraint",
                    models.CharField(
                        choices=[
                            ("all", "Tous"),
                            ("youth", "Jeunes"),
                            ("adult", "Adultes"),
                            ("team", "Équipe D2/D3"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Groupes",
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulée"),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_iso",
                    models.PositiveSmallIntegerField(
                        db_index=True, editable=False, verbose_name="Numéro de Semaine"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="core.category",
                        verbose_name="Categorie",
                    ),
                ),
                (
                    "coach",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sessions",
                        through="core.CoachAssignment",
                        to="core.member",
                        verbose_name="coach encadrant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="core.location",
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "recurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="core.recurrence",
                        verbose_name="Récurrence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance",
                "verbose_name_plural": "Séances",
                "ordering": ["-start_at"],
            },
        ),
        migrations.AddField(
            model_name="coachassignment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="coachassignment",
            constraint=models.UniqueConstraint(
                fields=("session", "coach"), name="unique_coach_per_session"
            ),
        ),
    ]
