# Generated by Django 5.2.7 on 2025-10-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="constraint",
        ),
        migrations.AddField(
            model_name="session",
            name="group",
            field=models.CharField(max_length=25, null=True, verbose_name="Groupes"),
        ),
    ]
