# Generated by Django 5.2.7 on 2025-10-24 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.RemoveConstraint(
            model_name='coachassignment',
            name='unique_coach_per_session',
        ),
        migrations.AlterField(
            model_name='member',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='core.category', verbose_name='Peut encadrer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.category', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Annulée'),
        ),
        migrations.AddConstraint(
            model_name='coachassignment',
            constraint=models.UniqueConstraint(fields=('session', 'coach'), name='unique_coach_per_session'),
        ),
    ]
