# Generated by Django 5.2.7 on 2025-10-30 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_session_constraint_session_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="coaches",
                to="core.category",
                verbose_name="Peut encadrer",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="duration_min",
            field=models.PositiveIntegerField(
                default=60, verbose_name="Durée en minute"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="group",
            field=models.CharField(max_length=25, null=True, verbose_name="Groupe"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["start_at"], name="core_sessio_start_a_fb46ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["is_cancelled"], name="core_sessio_is_canc_2ce52f_idx"
            ),
        ),
    ]
