# Generated by Django 5.2.7 on 2025-10-30 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_member_qualifications_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["category"], name="core_sessio_categor_a0597a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["location"], name="core_sessio_locatio_1f7c35_idx"
            ),
        ),
    ]
