# Generated by Django 5.2.7 on 2025-11-06 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_session_core_sessio_categor_a0597a_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceTypeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Catégorie de type de course",
                "verbose_name_plural": "Catégories de types de course",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="SportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Événement sportif",
                "verbose_name_plural": "Événements sportifs",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="RaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "distance_swim",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_bike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_run",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_other",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("elevation_bike", models.IntegerField(blank=True, null=True)),
                ("elevation_run", models.IntegerField(blank=True, null=True)),
                ("elevation_other", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="race_types",
                        to="core.racetypecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de course",
                "verbose_name_plural": "Types de course",
                "ordering": ["category__label", "label"],
                "unique_together": {("category", "label")},
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("custom_label", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "distance_swim",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_bike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_run",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_other",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("elevation_bike", models.IntegerField(blank=True, null=True)),
                ("elevation_run", models.IntegerField(blank=True, null=True)),
                ("elevation_other", models.IntegerField(blank=True, null=True)),
                (
                    "race_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="races",
                        to="core.racetype",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="core.sportevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["date"],
            },
        ),
    ]
