# Generated by Django 5.2.7 on 2025-11-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_racetypecategory_sportevent_racetype_race"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Discipline d'entrainement",
                "verbose_name_plural": "Disciplines d'entrainement",
            },
        ),
        migrations.AlterModelOptions(
            name="racetype",
            options={
                "verbose_name": "Type de course",
                "verbose_name_plural": "Types de course",
            },
        ),
        migrations.AlterUniqueTogether(
            name="racetype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="racetype",
            name="elevation_swim",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé natation (m)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.racetypecategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="distance_bike",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance en vélo (km)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="distance_other",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance autre (km)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="distance_run",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance en course à pied (km)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="distance_swim",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance en natation (km)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="elevation_bike",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé vélo (m)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="elevation_other",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé autre (m)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="elevation_run",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé course à pied (m)",
            ),
        ),
        migrations.AlterField(
            model_name="racetype",
            name="label",
            field=models.CharField(max_length=100, verbose_name="Nom du format"),
        ),
    ]
