# Generated by Django 5.2.7 on 2025-11-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_category_options_alter_racetype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="racetype",
            name="elevation_swim",
        ),
    ]
