# Generated by Django 5.2.7 on 2025-11-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_racetype_elevation_swim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="event",
        ),
        migrations.RemoveField(
            model_name="race",
            name="race_type",
        ),
        migrations.RemoveField(
            model_name="racetype",
            name="category",
        ),
        migrations.DeleteModel(
            name="SportEvent",
        ),
        migrations.DeleteModel(
            name="Race",
        ),
        migrations.DeleteModel(
            name="RaceType",
        ),
        migrations.DeleteModel(
            name="RaceTypeCategory",
        ),
    ]
