# Generated by Django 5.2.7 on 2025-11-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="Nom du format"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "distance_swim",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Distance en natation (km)",
                    ),
                ),
                (
                    "distance_bike",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Distance en vélo (km)",
                    ),
                ),
                (
                    "distance_run",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Distance en course à pied (km)",
                    ),
                ),
                (
                    "distance_other",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Distance autre (km)",
                    ),
                ),
                (
                    "elevation_bike",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Dénivelé vélo (m)",
                    ),
                ),
                (
                    "elevation_run",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Dénivelé course à pied (m)",
                    ),
                ),
                (
                    "elevation_other",
                    models.FloatField(
                        blank=True,
                        help_text="Laisser vide si non applicable",
                        null=True,
                        verbose_name="Dénivelé autre (m)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de course",
                "verbose_name_plural": "Types de course",
            },
        ),
        migrations.CreateModel(
            name="RaceTypeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Catégorie de type de course",
                "verbose_name_plural": "Catégories de types de course",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("custom_label", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "distance_swim",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_bike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_run",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distance_other",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("elevation_bike", models.IntegerField(blank=True, null=True)),
                ("elevation_run", models.IntegerField(blank=True, null=True)),
                ("elevation_other", models.IntegerField(blank=True, null=True)),
                (
                    "race_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="races",
                        to="trouvetacourse.racetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["start_date"],
            },
        ),
        migrations.AddField(
            model_name="racetype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trouvetacourse.racetypecategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.CreateModel(
            name="SportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'événement"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "race_types",
                    models.ManyToManyField(
                        blank=True,
                        through="trouvetacourse.Race",
                        to="trouvetacourse.racetype",
                        verbose_name="Courses proposées",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement sportif",
                "verbose_name_plural": "Événements sportifs",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="race",
            name="sport_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="races",
                to="trouvetacourse.sportevent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="race",
            unique_together={("sport_event", "race_type")},
        ),
    ]
