# Generated by Django 5.2.7 on 2025-11-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trouvetacourse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="racetypecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Catégorie de type de course",
                "verbose_name_plural": "Catégories de types de course",
            },
        ),
        migrations.RenameField(
            model_name="racetype",
            old_name="label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="racetypecategory",
            old_name="label",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="race",
            name="custom_label",
        ),
        migrations.AddField(
            model_name="race",
            name="custom_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom optionnel"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="race",
            name="distance_bike",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance en vélo (km)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="distance_other",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance autre (km)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="distance_run",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Distance en course à pied (km)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="distance_swim",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable ou si ",
                null=True,
                verbose_name="Distance en natation (km)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="elevation_bike",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé vélo (m)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="elevation_other",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé autre (m)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="elevation_run",
            field=models.FloatField(
                blank=True,
                help_text="Laisser vide si non applicable",
                null=True,
                verbose_name="Dénivelé course à pied (m)",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="races",
                to="trouvetacourse.racetype",
                verbose_name="Type de course",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="sport_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="races",
                to="trouvetacourse.sportevent",
                verbose_name="Événement sportif",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la course"
            ),
        ),
    ]
